//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Localization.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccessibilityQuery.
        /// </summary>
        public static string AccessibilityQuery {
            get {
                return ResourceManager.GetString("AccessibilityQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccessibilityQueryScreenTip.
        /// </summary>
        public static string AccessibilityQueryScreenTip {
            get {
                return ResourceManager.GetString("AccessibilityQueryScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionDomainGroupBox.
        /// </summary>
        public static string ActionDomainGroupBox {
            get {
                return ResourceManager.GetString("ActionDomainGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddActionButton.
        /// </summary>
        public static string ActionDropDown {
            get {
                return ResourceManager.GetString("ActionDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionDropdownScreenTip.
        /// </summary>
        public static string ActionDropDownScreenTip {
            get {
                return ResourceManager.GetString("ActionDropDownScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionScreenTip.
        /// </summary>
        public static string ActionScreenTip {
            get {
                return ResourceManager.GetString("ActionScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddActionButton.
        /// </summary>
        public static string AddActionButton {
            get {
                return ResourceManager.GetString("AddActionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddActionCancelButton.
        /// </summary>
        public static string AddActionCancelButton {
            get {
                return ResourceManager.GetString("AddActionCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddActionConfirmButton.
        /// </summary>
        public static string AddActionConfirmButton {
            get {
                return ResourceManager.GetString("AddActionConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddActionPrompt.
        /// </summary>
        public static string AddActionPrompt {
            get {
                return ResourceManager.GetString("AddActionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddActionStatementDropDown.
        /// </summary>
        public static string AddActionStatementDropDown {
            get {
                return ResourceManager.GetString("AddActionStatementDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddActionStatementDropDownScreenTip.
        /// </summary>
        public static string AddActionStatementDropDownScreenTip {
            get {
                return ResourceManager.GetString("AddActionStatementDropDownScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddActionTitle.
        /// </summary>
        public static string AddActionTitle {
            get {
                return ResourceManager.GetString("AddActionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddCompoundActionButton.
        /// </summary>
        public static string AddCompoundActionButton {
            get {
                return ResourceManager.GetString("AddCompoundActionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddFluentButton.
        /// </summary>
        public static string AddFluentButton {
            get {
                return ResourceManager.GetString("AddFluentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddFluentCancelButton.
        /// </summary>
        public static string AddFluentCancelButton {
            get {
                return ResourceManager.GetString("AddFluentCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddFluentConfirmButton.
        /// </summary>
        public static string AddFluentConfirmButton {
            get {
                return ResourceManager.GetString("AddFluentConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddFluentPrompt.
        /// </summary>
        public static string AddFluentPrompt {
            get {
                return ResourceManager.GetString("AddFluentPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddFluentTitle.
        /// </summary>
        public static string AddFluentTitle {
            get {
                return ResourceManager.GetString("AddFluentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddQueryStatementDropDown.
        /// </summary>
        public static string AddQueryStatementDropDown {
            get {
                return ResourceManager.GetString("AddQueryStatementDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddQueryStatementDropDownScreenTip.
        /// </summary>
        public static string AddQueryStatementDropDownScreenTip {
            get {
                return ResourceManager.GetString("AddQueryStatementDropDownScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlternativeButton.
        /// </summary>
        public static string AlternativeButton {
            get {
                return ResourceManager.GetString("AlternativeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlternativeButtonScreenTip.
        /// </summary>
        public static string AlternativeButtonScreenTip {
            get {
                return ResourceManager.GetString("AlternativeButtonScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalculateButton.
        /// </summary>
        public static string CalculateButton {
            get {
                return ResourceManager.GetString("CalculateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalculateButtonScreenTip.
        /// </summary>
        public static string CalculateButtonScreenTip {
            get {
                return ResourceManager.GetString("CalculateButtonScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CannotAddFormulaError.
        /// </summary>
        public static string CannotAddFormulaError {
            get {
                return ResourceManager.GetString("CannotAddFormulaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChooseLanguage.
        /// </summary>
        public static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClearButton.
        /// </summary>
        public static string ClearButton {
            get {
                return ResourceManager.GetString("ClearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClearButtonScreenTip.
        /// </summary>
        public static string ClearButtonScreenTip {
            get {
                return ResourceManager.GetString("ClearButtonScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloseButton.
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloseButtonScreenTip.
        /// </summary>
        public static string CloseButtonScreenTip {
            get {
                return ResourceManager.GetString("CloseButtonScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionalEffectStatement.
        /// </summary>
        public static string ConditionalEffectStatement {
            get {
                return ResourceManager.GetString("ConditionalEffectStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionalEffectStatementScreenTip.
        /// </summary>
        public static string ConditionalEffectStatementScreenTip {
            get {
                return ResourceManager.GetString("ConditionalEffectStatementScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionalFluentReleaseStatement.
        /// </summary>
        public static string ConditionalFluentReleaseStatement {
            get {
                return ResourceManager.GetString("ConditionalFluentReleaseStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionalFluentReleaseStatementScreenTip.
        /// </summary>
        public static string ConditionalFluentReleaseStatementScreenTip {
            get {
                return ResourceManager.GetString("ConditionalFluentReleaseStatementScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionalImpossibilityStatement.
        /// </summary>
        public static string ConditionalImpossibilityStatement {
            get {
                return ResourceManager.GetString("ConditionalImpossibilityStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionalImpossibilityStatementScreenTip.
        /// </summary>
        public static string ConditionalImpossibilityStatementScreenTip {
            get {
                return ResourceManager.GetString("ConditionalImpossibilityStatementScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConjunctionButton.
        /// </summary>
        public static string ConjunctionButton {
            get {
                return ResourceManager.GetString("ConjunctionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConjunctionButtonScreenTip.
        /// </summary>
        public static string ConjunctionButtonScreenTip {
            get {
                return ResourceManager.GetString("ConjunctionButtonScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constraint.
        /// </summary>
        public static string Constraint {
            get {
                return ResourceManager.GetString("Constraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConstraintScreenTip.
        /// </summary>
        public static string ConstraintScreenTip {
            get {
                return ResourceManager.GetString("ConstraintScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConstraintStatement.
        /// </summary>
        public static string ConstraintStatement {
            get {
                return ResourceManager.GetString("ConstraintStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConstraintStatementScreenTip.
        /// </summary>
        public static string ConstraintStatementScreenTip {
            get {
                return ResourceManager.GetString("ConstraintStatementScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditTab.
        /// </summary>
        public static string EditTab {
            get {
                return ResourceManager.GetString("EditTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EffectStatement.
        /// </summary>
        public static string EffectStatement {
            get {
                return ResourceManager.GetString("EffectStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EquivalencyButton.
        /// </summary>
        public static string EquivalenceButton {
            get {
                return ResourceManager.GetString("EquivalenceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EquivalenceButtonScreenTip.
        /// </summary>
        public static string EquivalenceButtonScreenTip {
            get {
                return ResourceManager.GetString("EquivalenceButtonScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorMessageItem.
        /// </summary>
        public static string ErrorMessageItem {
            get {
                return ResourceManager.GetString("ErrorMessageItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExecutabilityQuery.
        /// </summary>
        public static string ExecutabilityQuery {
            get {
                return ResourceManager.GetString("ExecutabilityQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExistentialExecutabilityQuery.
        /// </summary>
        public static string ExistentialExecutabilityQuery {
            get {
                return ResourceManager.GetString("ExistentialExecutabilityQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExistentialExecutabilityQueryScreenTip.
        /// </summary>
        public static string ExistentialExecutabilityQueryScreenTip {
            get {
                return ResourceManager.GetString("ExistentialExecutabilityQueryScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExistentialValueQuery.
        /// </summary>
        public static string ExistentialValueQuery {
            get {
                return ResourceManager.GetString("ExistentialValueQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExistentialValueQueryScreenTip.
        /// </summary>
        public static string ExistentialValueQueryScreenTip {
            get {
                return ResourceManager.GetString("ExistentialValueQueryScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExportButton.
        /// </summary>
        public static string ExportButton {
            get {
                return ResourceManager.GetString("ExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExportButtonScreenTip.
        /// </summary>
        public static string ExportButtonScreenTip {
            get {
                return ResourceManager.GetString("ExportButtonScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FalsityButton.
        /// </summary>
        public static string FalsityButton {
            get {
                return ResourceManager.GetString("FalsityButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FalsityButtonScreenTip.
        /// </summary>
        public static string FalsityButtonScreenTip {
            get {
                return ResourceManager.GetString("FalsityButtonScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluent.
        /// </summary>
        public static string Fluent {
            get {
                return ResourceManager.GetString("Fluent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FluentDropDown.
        /// </summary>
        public static string FluentDropDown {
            get {
                return ResourceManager.GetString("FluentDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FluentDropDownScreenTip.
        /// </summary>
        public static string FluentDropDownScreenTip {
            get {
                return ResourceManager.GetString("FluentDropDownScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FluentReleaseStatement.
        /// </summary>
        public static string FluentReleaseStatement {
            get {
                return ResourceManager.GetString("FluentReleaseStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FluentScreenTip.
        /// </summary>
        public static string FluentScreenTip {
            get {
                return ResourceManager.GetString("FluentScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FluentSpecificationStatement.
        /// </summary>
        public static string FluentSpecificationStatement {
            get {
                return ResourceManager.GetString("FluentSpecificationStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FluentSpecificationStatementScreenTip.
        /// </summary>
        public static string FluentSpecificationStatementScreenTip {
            get {
                return ResourceManager.GetString("FluentSpecificationStatementScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FormulaGroupBox.
        /// </summary>
        public static string FormulaGroupBox {
            get {
                return ResourceManager.GetString("FormulaGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeneralExecutabilityQuery.
        /// </summary>
        public static string GeneralExecutabilityQuery {
            get {
                return ResourceManager.GetString("GeneralExecutabilityQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeneralExecutabilityQueryScreenTip.
        /// </summary>
        public static string GeneralExecutabilityQueryScreenTip {
            get {
                return ResourceManager.GetString("GeneralExecutabilityQueryScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeneralValueQuery.
        /// </summary>
        public static string GeneralValueQuery {
            get {
                return ResourceManager.GetString("GeneralValueQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeneralValueQueryScreenTip.
        /// </summary>
        public static string GeneralValueQueryScreenTip {
            get {
                return ResourceManager.GetString("GeneralValueQueryScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GrammarTab.
        /// </summary>
        public static string GrammarTab {
            get {
                return ResourceManager.GetString("GrammarTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImplicationButton.
        /// </summary>
        public static string ImplicationButton {
            get {
                return ResourceManager.GetString("ImplicationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImplicationButtonScreenTip.
        /// </summary>
        public static string ImplicationButtonScreenTip {
            get {
                return ResourceManager.GetString("ImplicationButtonScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImportButton.
        /// </summary>
        public static string ImportButton {
            get {
                return ResourceManager.GetString("ImportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImportButtonScreenTip.
        /// </summary>
        public static string ImportButtonScreenTip {
            get {
                return ResourceManager.GetString("ImportButtonScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InitialCondition.
        /// </summary>
        public static string InitialCondition {
            get {
                return ResourceManager.GetString("InitialCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InitialConditionScreenTip.
        /// </summary>
        public static string InitialConditionScreenTip {
            get {
                return ResourceManager.GetString("InitialConditionScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InitialValueStatement.
        /// </summary>
        public static string InitialValueStatement {
            get {
                return ResourceManager.GetString("InitialValueStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InitialValueStatementScreenTip.
        /// </summary>
        public static string InitialValueStatementScreenTip {
            get {
                return ResourceManager.GetString("InitialValueStatementScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LanguageGroupBox.
        /// </summary>
        public static string LanguageGroupBox {
            get {
                return ResourceManager.GetString("LanguageGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NegationButton.
        /// </summary>
        public static string NegationButton {
            get {
                return ResourceManager.GetString("NegationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NegationButtonScreenTip.
        /// </summary>
        public static string NegationButtonScreenTip {
            get {
                return ResourceManager.GetString("NegationButtonScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObservationCondition.
        /// </summary>
        public static string ObservationCondition {
            get {
                return ResourceManager.GetString("ObservationCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObservationConditionScreenTip.
        /// </summary>
        public static string ObservationConditionScreenTip {
            get {
                return ResourceManager.GetString("ObservationConditionScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObservationStatement.
        /// </summary>
        public static string ObservationStatement {
            get {
                return ResourceManager.GetString("ObservationStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObservationStatementScreenTip.
        /// </summary>
        public static string ObservationStatementScreenTip {
            get {
                return ResourceManager.GetString("ObservationStatementScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptionsTab.
        /// </summary>
        public static string OptionsTab {
            get {
                return ResourceManager.GetString("OptionsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcondition.
        /// </summary>
        public static string Postcondition {
            get {
                return ResourceManager.GetString("Postcondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostconditionScreenTip.
        /// </summary>
        public static string PostconditionScreenTip {
            get {
                return ResourceManager.GetString("PostconditionScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precondition.
        /// </summary>
        public static string Precondition {
            get {
                return ResourceManager.GetString("Precondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreconditionScreenTip.
        /// </summary>
        public static string PreconditionScreenTip {
            get {
                return ResourceManager.GetString("PreconditionScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        public static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProgramScreenTip.
        /// </summary>
        public static string ProgramScreenTip {
            get {
                return ResourceManager.GetString("ProgramScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QueryClauseGroupBox.
        /// </summary>
        public static string QueryClauseGroupBox {
            get {
                return ResourceManager.GetString("QueryClauseGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemGroupBox.
        /// </summary>
        public static string SystemGroupBox {
            get {
                return ResourceManager.GetString("SystemGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TargetScreenTip.
        /// </summary>
        public static string TargetScreenTip {
            get {
                return ResourceManager.GetString("TargetScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TruthButton.
        /// </summary>
        public static string TruthButton {
            get {
                return ResourceManager.GetString("TruthButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TruthButtonScreenTip.
        /// </summary>
        public static string TruthButtonScreenTip {
            get {
                return ResourceManager.GetString("TruthButtonScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnconditionalEffectStatement.
        /// </summary>
        public static string UnconditionalEffectStatement {
            get {
                return ResourceManager.GetString("UnconditionalEffectStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnconditionalEffectStatementScreenTip.
        /// </summary>
        public static string UnconditionalEffectStatementScreenTip {
            get {
                return ResourceManager.GetString("UnconditionalEffectStatementScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnconditionalFluentReleaseStatement.
        /// </summary>
        public static string UnconditionalFluentReleaseStatement {
            get {
                return ResourceManager.GetString("UnconditionalFluentReleaseStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnconditionalFluentReleaseStatementScreenTip.
        /// </summary>
        public static string UnconditionalFluentReleaseStatementScreenTip {
            get {
                return ResourceManager.GetString("UnconditionalFluentReleaseStatementScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnconditionalImpossibilityStatement.
        /// </summary>
        public static string UnconditionalImpossibilityStatement {
            get {
                return ResourceManager.GetString("UnconditionalImpossibilityStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnconditionalImpossibilityStatementScreenTip.
        /// </summary>
        public static string UnconditionalImpossibilityStatementScreenTip {
            get {
                return ResourceManager.GetString("UnconditionalImpossibilityStatementScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValueCondition.
        /// </summary>
        public static string ValueCondition {
            get {
                return ResourceManager.GetString("ValueCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValueConditionScreenTip.
        /// </summary>
        public static string ValueConditionScreenTip {
            get {
                return ResourceManager.GetString("ValueConditionScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValueQuery.
        /// </summary>
        public static string ValueQuery {
            get {
                return ResourceManager.GetString("ValueQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValueStatement.
        /// </summary>
        public static string ValueStatement {
            get {
                return ResourceManager.GetString("ValueStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValueStatementScreenTip.
        /// </summary>
        public static string ValueStatementScreenTip {
            get {
                return ResourceManager.GetString("ValueStatementScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowTitle.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
