//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Localization.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccessibilityQuery.
        /// </summary>
        public static string AccessibilityQuery {
            get {
                return ResourceManager.GetString("AccessibilityQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccessibilityQueryScreenTip.
        /// </summary>
        public static string AccessibilityQueryScreenTip {
            get {
                return ResourceManager.GetString("AccessibilityQueryScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccessibilityQueryTargetError.
        /// </summary>
        public static string AccessibilityQueryTargetError {
            get {
                return ResourceManager.GetString("AccessibilityQueryTargetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionDomainGroupBox.
        /// </summary>
        public static string ActionDomainGroupBox {
            get {
                return ResourceManager.GetString("ActionDomainGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse action domain:.
        /// </summary>
        public static string ActionDomainParseErrorPrefix {
            get {
                return ResourceManager.GetString("ActionDomainParseErrorPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddActionButton.
        /// </summary>
        public static string ActionDropDown {
            get {
                return ResourceManager.GetString("ActionDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionDropdownScreenTip.
        /// </summary>
        public static string ActionDropDownScreenTip {
            get {
                return ResourceManager.GetString("ActionDropDownScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionErrorPrefix.
        /// </summary>
        public static string ActionErrorPrefix {
            get {
                return ResourceManager.GetString("ActionErrorPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionErrorSuffix.
        /// </summary>
        public static string ActionErrorSuffix {
            get {
                return ResourceManager.GetString("ActionErrorSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string ActionNotDefinedInActionDomainPrefix {
            get {
                return ResourceManager.GetString("ActionNotDefinedInActionDomainPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not defined in action domain..
        /// </summary>
        public static string ActionNotDefinedInActionDomainSuffix {
            get {
                return ResourceManager.GetString("ActionNotDefinedInActionDomainSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionScreenTip.
        /// </summary>
        public static string ActionScreenTip {
            get {
                return ResourceManager.GetString("ActionScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionValueError.
        /// </summary>
        public static string ActionValueError {
            get {
                return ResourceManager.GetString("ActionValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddActionButton.
        /// </summary>
        public static string AddActionButton {
            get {
                return ResourceManager.GetString("AddActionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddActionCancelButton.
        /// </summary>
        public static string AddActionCancelButton {
            get {
                return ResourceManager.GetString("AddActionCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddActionConfirmButton.
        /// </summary>
        public static string AddActionConfirmButton {
            get {
                return ResourceManager.GetString("AddActionConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddActionPrompt.
        /// </summary>
        public static string AddActionPrompt {
            get {
                return ResourceManager.GetString("AddActionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddActionStatementDropDown.
        /// </summary>
        public static string AddActionStatementDropDown {
            get {
                return ResourceManager.GetString("AddActionStatementDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddActionStatementDropDownScreenTip.
        /// </summary>
        public static string AddActionStatementDropDownScreenTip {
            get {
                return ResourceManager.GetString("AddActionStatementDropDownScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddActionTitle.
        /// </summary>
        public static string AddActionTitle {
            get {
                return ResourceManager.GetString("AddActionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddCompoundActionButton.
        /// </summary>
        public static string AddCompoundActionButton {
            get {
                return ResourceManager.GetString("AddCompoundActionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddCompoundActionButtonScreenTip.
        /// </summary>
        public static string AddCompoundActionButtonScreenTip {
            get {
                return ResourceManager.GetString("AddCompoundActionButtonScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddCompoundActionButtonUnbroken.
        /// </summary>
        public static string AddCompoundActionButtonUnbroken {
            get {
                return ResourceManager.GetString("AddCompoundActionButtonUnbroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddFluentButton.
        /// </summary>
        public static string AddFluentButton {
            get {
                return ResourceManager.GetString("AddFluentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddFluentCancelButton.
        /// </summary>
        public static string AddFluentCancelButton {
            get {
                return ResourceManager.GetString("AddFluentCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddFluentConfirmButton.
        /// </summary>
        public static string AddFluentConfirmButton {
            get {
                return ResourceManager.GetString("AddFluentConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddFluentPrompt.
        /// </summary>
        public static string AddFluentPrompt {
            get {
                return ResourceManager.GetString("AddFluentPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddFluentTitle.
        /// </summary>
        public static string AddFluentTitle {
            get {
                return ResourceManager.GetString("AddFluentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddQueryStatementDropDown.
        /// </summary>
        public static string AddQueryStatementDropDown {
            get {
                return ResourceManager.GetString("AddQueryStatementDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddQueryStatementDropDownScreenTip.
        /// </summary>
        public static string AddQueryStatementDropDownScreenTip {
            get {
                return ResourceManager.GetString("AddQueryStatementDropDownScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlternativeButton.
        /// </summary>
        public static string AlternativeButton {
            get {
                return ResourceManager.GetString("AlternativeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlternativeButtonScreenTip.
        /// </summary>
        public static string AlternativeButtonScreenTip {
            get {
                return ResourceManager.GetString("AlternativeButtonScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlternativeLeftFormulaError.
        /// </summary>
        public static string AlternativeLeftFormulaError {
            get {
                return ResourceManager.GetString("AlternativeLeftFormulaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlternativeRightFormulaError.
        /// </summary>
        public static string AlternativeRightFormulaError {
            get {
                return ResourceManager.GetString("AlternativeRightFormulaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalculateButton.
        /// </summary>
        public static string CalculateButton {
            get {
                return ResourceManager.GetString("CalculateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalculateButtonScreenTip.
        /// </summary>
        public static string CalculateButtonScreenTip {
            get {
                return ResourceManager.GetString("CalculateButtonScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelButton.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelButtonScreenTip.
        /// </summary>
        public static string CancelButtonScreenTip {
            get {
                return ResourceManager.GetString("CancelButtonScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CannotAddActionError.
        /// </summary>
        public static string CannotAddActionError {
            get {
                return ResourceManager.GetString("CannotAddActionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CannotAddCompoundActionError.
        /// </summary>
        public static string CannotAddCompoundActionError {
            get {
                return ResourceManager.GetString("CannotAddCompoundActionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CannotAddFormulaError.
        /// </summary>
        public static string CannotAddFormulaError {
            get {
                return ResourceManager.GetString("CannotAddFormulaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChooseLanguage.
        /// </summary>
        public static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClearButton.
        /// </summary>
        public static string ClearButton {
            get {
                return ResourceManager.GetString("ClearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClearButtonScreenTip.
        /// </summary>
        public static string ClearButtonScreenTip {
            get {
                return ResourceManager.GetString("ClearButtonScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloseButton.
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloseButtonScreenTip.
        /// </summary>
        public static string CloseButtonScreenTip {
            get {
                return ResourceManager.GetString("CloseButtonScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompoundActionActionError.
        /// </summary>
        public static string CompoundActionActionError {
            get {
                return ResourceManager.GetString("CompoundActionActionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompoundActionActionsError.
        /// </summary>
        public static string CompoundActionActionsError {
            get {
                return ResourceManager.GetString("CompoundActionActionsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionalEffectStatement.
        /// </summary>
        public static string ConditionalEffectStatement {
            get {
                return ResourceManager.GetString("ConditionalEffectStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionalEffectStatementActionError.
        /// </summary>
        public static string ConditionalEffectStatementActionError {
            get {
                return ResourceManager.GetString("ConditionalEffectStatementActionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionalEffectStatementPostconditionError.
        /// </summary>
        public static string ConditionalEffectStatementPostconditionError {
            get {
                return ResourceManager.GetString("ConditionalEffectStatementPostconditionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionalEffectStatementPreconditionError.
        /// </summary>
        public static string ConditionalEffectStatementPreconditionError {
            get {
                return ResourceManager.GetString("ConditionalEffectStatementPreconditionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionalEffectStatementScreenTip.
        /// </summary>
        public static string ConditionalEffectStatementScreenTip {
            get {
                return ResourceManager.GetString("ConditionalEffectStatementScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionalFluentReleaseStatement.
        /// </summary>
        public static string ConditionalFluentReleaseStatement {
            get {
                return ResourceManager.GetString("ConditionalFluentReleaseStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionalFluentReleaseStatementActionError.
        /// </summary>
        public static string ConditionalFluentReleaseStatementActionError {
            get {
                return ResourceManager.GetString("ConditionalFluentReleaseStatementActionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionalFluentReleaseStatementFluentError.
        /// </summary>
        public static string ConditionalFluentReleaseStatementFluentError {
            get {
                return ResourceManager.GetString("ConditionalFluentReleaseStatementFluentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionalFluentReleaseStatementPreconditionError.
        /// </summary>
        public static string ConditionalFluentReleaseStatementPreconditionError {
            get {
                return ResourceManager.GetString("ConditionalFluentReleaseStatementPreconditionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionalFluentReleaseStatementScreenTip.
        /// </summary>
        public static string ConditionalFluentReleaseStatementScreenTip {
            get {
                return ResourceManager.GetString("ConditionalFluentReleaseStatementScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionalImpossibilityStatement.
        /// </summary>
        public static string ConditionalImpossibilityStatement {
            get {
                return ResourceManager.GetString("ConditionalImpossibilityStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionalImpossibilityStatementActionError.
        /// </summary>
        public static string ConditionalImpossibilityStatementActionError {
            get {
                return ResourceManager.GetString("ConditionalImpossibilityStatementActionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionalImpossibilityStatementPreconditionError.
        /// </summary>
        public static string ConditionalImpossibilityStatementPreconditionError {
            get {
                return ResourceManager.GetString("ConditionalImpossibilityStatementPreconditionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionalImpossibilityStatementScreenTip.
        /// </summary>
        public static string ConditionalImpossibilityStatementScreenTip {
            get {
                return ResourceManager.GetString("ConditionalImpossibilityStatementScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConjunctionButton.
        /// </summary>
        public static string ConjunctionButton {
            get {
                return ResourceManager.GetString("ConjunctionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConjunctionButtonScreenTip.
        /// </summary>
        public static string ConjunctionButtonScreenTip {
            get {
                return ResourceManager.GetString("ConjunctionButtonScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConjunctionLeftFormulaError.
        /// </summary>
        public static string ConjunctionLeftFormulaError {
            get {
                return ResourceManager.GetString("ConjunctionLeftFormulaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConjunctionRightFormulaError.
        /// </summary>
        public static string ConjunctionRightFormulaError {
            get {
                return ResourceManager.GetString("ConjunctionRightFormulaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConstantValueError.
        /// </summary>
        public static string ConstantValueError {
            get {
                return ResourceManager.GetString("ConstantValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constraint.
        /// </summary>
        public static string Constraint {
            get {
                return ResourceManager.GetString("Constraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConstraintScreenTip.
        /// </summary>
        public static string ConstraintScreenTip {
            get {
                return ResourceManager.GetString("ConstraintScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConstraintStatement.
        /// </summary>
        public static string ConstraintStatement {
            get {
                return ResourceManager.GetString("ConstraintStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConstraintStatementConditionError.
        /// </summary>
        public static string ConstraintStatementConditionError {
            get {
                return ResourceManager.GetString("ConstraintStatementConditionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConstraintStatementScreenTip.
        /// </summary>
        public static string ConstraintStatementScreenTip {
            get {
                return ResourceManager.GetString("ConstraintStatementScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditButton.
        /// </summary>
        public static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditTab.
        /// </summary>
        public static string EditTab {
            get {
                return ResourceManager.GetString("EditTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EffectStatement.
        /// </summary>
        public static string EffectStatement {
            get {
                return ResourceManager.GetString("EffectStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EffectStatementActionError.
        /// </summary>
        public static string EffectStatementActionError {
            get {
                return ResourceManager.GetString("EffectStatementActionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EffectStatementPostconditionError.
        /// </summary>
        public static string EffectStatementPostconditionError {
            get {
                return ResourceManager.GetString("EffectStatementPostconditionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EffectStatementPreconditionError.
        /// </summary>
        public static string EffectStatementPreconditionError {
            get {
                return ResourceManager.GetString("EffectStatementPreconditionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EquivalencyButton.
        /// </summary>
        public static string EquivalenceButton {
            get {
                return ResourceManager.GetString("EquivalenceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EquivalenceButtonScreenTip.
        /// </summary>
        public static string EquivalenceButtonScreenTip {
            get {
                return ResourceManager.GetString("EquivalenceButtonScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EquivalenceLeftFormulaError.
        /// </summary>
        public static string EquivalenceLeftFormulaError {
            get {
                return ResourceManager.GetString("EquivalenceLeftFormulaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EquivalenceRightFormulaError.
        /// </summary>
        public static string EquivalenceRightFormulaError {
            get {
                return ResourceManager.GetString("EquivalenceRightFormulaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorMessageItem.
        /// </summary>
        public static string ErrorMessageItem {
            get {
                return ResourceManager.GetString("ErrorMessageItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExecutabilityQuery.
        /// </summary>
        public static string ExecutabilityQuery {
            get {
                return ResourceManager.GetString("ExecutabilityQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExistentialExecutabilityQuery.
        /// </summary>
        public static string ExistentialExecutabilityQuery {
            get {
                return ResourceManager.GetString("ExistentialExecutabilityQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExistentialExecutabilityQueryProgramError.
        /// </summary>
        public static string ExistentialExecutabilityQueryProgramError {
            get {
                return ResourceManager.GetString("ExistentialExecutabilityQueryProgramError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExistentialExecutabilityQueryScreenTip.
        /// </summary>
        public static string ExistentialExecutabilityQueryScreenTip {
            get {
                return ResourceManager.GetString("ExistentialExecutabilityQueryScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExistentialValueQuery.
        /// </summary>
        public static string ExistentialValueQuery {
            get {
                return ResourceManager.GetString("ExistentialValueQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExistentialValueQueryProgramError.
        /// </summary>
        public static string ExistentialValueQueryProgramError {
            get {
                return ResourceManager.GetString("ExistentialValueQueryProgramError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExistentialValueQueryScreenTip.
        /// </summary>
        public static string ExistentialValueQueryScreenTip {
            get {
                return ResourceManager.GetString("ExistentialValueQueryScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExistentialValueQueryTargetError.
        /// </summary>
        public static string ExistentialValueQueryTargetError {
            get {
                return ResourceManager.GetString("ExistentialValueQueryTargetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExportButton.
        /// </summary>
        public static string ExportButton {
            get {
                return ResourceManager.GetString("ExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExportButtonScreenTip.
        /// </summary>
        public static string ExportButtonScreenTip {
            get {
                return ResourceManager.GetString("ExportButtonScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FalsityButton.
        /// </summary>
        public static string FalsityButton {
            get {
                return ResourceManager.GetString("FalsityButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FalsityButtonScreenTip.
        /// </summary>
        public static string FalsityButtonScreenTip {
            get {
                return ResourceManager.GetString("FalsityButtonScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluent.
        /// </summary>
        public static string Fluent {
            get {
                return ResourceManager.GetString("Fluent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FluentDropDown.
        /// </summary>
        public static string FluentDropDown {
            get {
                return ResourceManager.GetString("FluentDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FluentDropDownScreenTip.
        /// </summary>
        public static string FluentDropDownScreenTip {
            get {
                return ResourceManager.GetString("FluentDropDownScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FluentErrorPrefix.
        /// </summary>
        public static string FluentErrorPrefix {
            get {
                return ResourceManager.GetString("FluentErrorPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FluentErrorSuffix.
        /// </summary>
        public static string FluentErrorSuffix {
            get {
                return ResourceManager.GetString("FluentErrorSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluent.
        /// </summary>
        public static string FluentNotDefinedInActionDomainPrefix {
            get {
                return ResourceManager.GetString("FluentNotDefinedInActionDomainPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not defined in action domain..
        /// </summary>
        public static string FluentNotDefinedInActionDomainSuffix {
            get {
                return ResourceManager.GetString("FluentNotDefinedInActionDomainSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FluentReleaseActionError.
        /// </summary>
        public static string FluentReleaseActionError {
            get {
                return ResourceManager.GetString("FluentReleaseActionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FluentReleaseFluentError.
        /// </summary>
        public static string FluentReleaseFluentError {
            get {
                return ResourceManager.GetString("FluentReleaseFluentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FluentReleasePreconditionError.
        /// </summary>
        public static string FluentReleasePreconditionError {
            get {
                return ResourceManager.GetString("FluentReleasePreconditionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FluentReleaseStatement.
        /// </summary>
        public static string FluentReleaseStatement {
            get {
                return ResourceManager.GetString("FluentReleaseStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FluentScreenTip.
        /// </summary>
        public static string FluentScreenTip {
            get {
                return ResourceManager.GetString("FluentScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FluentSpecificationStatement.
        /// </summary>
        public static string FluentSpecificationStatement {
            get {
                return ResourceManager.GetString("FluentSpecificationStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FluentSpecificationStatementFluentError.
        /// </summary>
        public static string FluentSpecificationStatementFluentError {
            get {
                return ResourceManager.GetString("FluentSpecificationStatementFluentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FluentSpecificationStatementScreenTip.
        /// </summary>
        public static string FluentSpecificationStatementScreenTip {
            get {
                return ResourceManager.GetString("FluentSpecificationStatementScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FormulaGroupBox.
        /// </summary>
        public static string FormulaGroupBox {
            get {
                return ResourceManager.GetString("FormulaGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FormulaTypeErrorPrefix.
        /// </summary>
        public static string FormulaTypeErrorPrefix {
            get {
                return ResourceManager.GetString("FormulaTypeErrorPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FormulaTypeErrorSuffix.
        /// </summary>
        public static string FormulaTypeErrorSuffix {
            get {
                return ResourceManager.GetString("FormulaTypeErrorSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeneralExecutabilityQuery.
        /// </summary>
        public static string GeneralExecutabilityQuery {
            get {
                return ResourceManager.GetString("GeneralExecutabilityQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeneralExecutabilityQueryProgramError.
        /// </summary>
        public static string GeneralExecutabilityQueryProgramError {
            get {
                return ResourceManager.GetString("GeneralExecutabilityQueryProgramError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeneralExecutabilityQueryScreenTip.
        /// </summary>
        public static string GeneralExecutabilityQueryScreenTip {
            get {
                return ResourceManager.GetString("GeneralExecutabilityQueryScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeneralValueQuery.
        /// </summary>
        public static string GeneralValueQuery {
            get {
                return ResourceManager.GetString("GeneralValueQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeneralValueQueryProgramError.
        /// </summary>
        public static string GeneralValueQueryProgramError {
            get {
                return ResourceManager.GetString("GeneralValueQueryProgramError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeneralValueQueryScreenTip.
        /// </summary>
        public static string GeneralValueQueryScreenTip {
            get {
                return ResourceManager.GetString("GeneralValueQueryScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeneralValueQueryTargetError.
        /// </summary>
        public static string GeneralValueQueryTargetError {
            get {
                return ResourceManager.GetString("GeneralValueQueryTargetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GrammarActionDomainInputHintText.
        /// </summary>
        public static string GrammarActionDomainInputHintText {
            get {
                return ResourceManager.GetString("GrammarActionDomainInputHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GrammarDeserializationFailed.
        /// </summary>
        public static string GrammarDeserializationFailed {
            get {
                return ResourceManager.GetString("GrammarDeserializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GrammarQuerySetInputHintText.
        /// </summary>
        public static string GrammarQuerySetInputHintText {
            get {
                return ResourceManager.GetString("GrammarQuerySetInputHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GrammarSerializationFailed.
        /// </summary>
        public static string GrammarSerializationFailed {
            get {
                return ResourceManager.GetString("GrammarSerializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GrammarTab.
        /// </summary>
        public static string GrammarTab {
            get {
                return ResourceManager.GetString("GrammarTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImplicationAntecedentError.
        /// </summary>
        public static string ImplicationAntecedentError {
            get {
                return ResourceManager.GetString("ImplicationAntecedentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImplicationButton.
        /// </summary>
        public static string ImplicationButton {
            get {
                return ResourceManager.GetString("ImplicationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImplicationButtonScreenTip.
        /// </summary>
        public static string ImplicationButtonScreenTip {
            get {
                return ResourceManager.GetString("ImplicationButtonScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImplicationConsequentError.
        /// </summary>
        public static string ImplicationConsequentError {
            get {
                return ResourceManager.GetString("ImplicationConsequentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImportButton.
        /// </summary>
        public static string ImportButton {
            get {
                return ResourceManager.GetString("ImportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImportButtonScreenTip.
        /// </summary>
        public static string ImportButtonScreenTip {
            get {
                return ResourceManager.GetString("ImportButtonScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InitialCondition.
        /// </summary>
        public static string InitialCondition {
            get {
                return ResourceManager.GetString("InitialCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InitialConditionScreenTip.
        /// </summary>
        public static string InitialConditionScreenTip {
            get {
                return ResourceManager.GetString("InitialConditionScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InitialValueStatement.
        /// </summary>
        public static string InitialValueStatement {
            get {
                return ResourceManager.GetString("InitialValueStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InitialValueStatementInitialConditionError.
        /// </summary>
        public static string InitialValueStatementInitialConditionError {
            get {
                return ResourceManager.GetString("InitialValueStatementInitialConditionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InitialValueStatementScreenTip.
        /// </summary>
        public static string InitialValueStatementScreenTip {
            get {
                return ResourceManager.GetString("InitialValueStatementScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LanguageGroupBox.
        /// </summary>
        public static string LanguageGroupBox {
            get {
                return ResourceManager.GetString("LanguageGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LiteralFluentError.
        /// </summary>
        public static string LiteralFluentError {
            get {
                return ResourceManager.GetString("LiteralFluentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NegationButton.
        /// </summary>
        public static string NegationButton {
            get {
                return ResourceManager.GetString("NegationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NegationButtonScreenTip.
        /// </summary>
        public static string NegationButtonScreenTip {
            get {
                return ResourceManager.GetString("NegationButtonScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NegationFormulaError.
        /// </summary>
        public static string NegationFormulaError {
            get {
                return ResourceManager.GetString("NegationFormulaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObservationCondition.
        /// </summary>
        public static string ObservationCondition {
            get {
                return ResourceManager.GetString("ObservationCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObservationConditionScreenTip.
        /// </summary>
        public static string ObservationConditionScreenTip {
            get {
                return ResourceManager.GetString("ObservationConditionScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObservationStatement.
        /// </summary>
        public static string ObservationStatement {
            get {
                return ResourceManager.GetString("ObservationStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObservationStatementActionError.
        /// </summary>
        public static string ObservationStatementActionError {
            get {
                return ResourceManager.GetString("ObservationStatementActionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObservationStatementConditionError.
        /// </summary>
        public static string ObservationStatementConditionError {
            get {
                return ResourceManager.GetString("ObservationStatementConditionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObservationStatementScreenTip.
        /// </summary>
        public static string ObservationStatementScreenTip {
            get {
                return ResourceManager.GetString("ObservationStatementScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptionsTab.
        /// </summary>
        public static string OptionsTab {
            get {
                return ResourceManager.GetString("OptionsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PogramCompoundActionError.
        /// </summary>
        public static string PogramCompoundActionError {
            get {
                return ResourceManager.GetString("PogramCompoundActionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcondition.
        /// </summary>
        public static string Postcondition {
            get {
                return ResourceManager.GetString("Postcondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostconditionScreenTip.
        /// </summary>
        public static string PostconditionScreenTip {
            get {
                return ResourceManager.GetString("PostconditionScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precondition.
        /// </summary>
        public static string Precondition {
            get {
                return ResourceManager.GetString("Precondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreconditionScreenTip.
        /// </summary>
        public static string PreconditionScreenTip {
            get {
                return ResourceManager.GetString("PreconditionScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        public static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProgramCompoundActionsError.
        /// </summary>
        public static string ProgramCompoundActionsError {
            get {
                return ResourceManager.GetString("ProgramCompoundActionsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProgramScreenTip.
        /// </summary>
        public static string ProgramScreenTip {
            get {
                return ResourceManager.GetString("ProgramScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QueryClauseGroupBox.
        /// </summary>
        public static string QueryClauseGroupBox {
            get {
                return ResourceManager.GetString("QueryClauseGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse query set:.
        /// </summary>
        public static string QuerySetParseErrorPrefix {
            get {
                return ResourceManager.GetString("QuerySetParseErrorPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScenarioDeserializationFailed.
        /// </summary>
        public static string ScenarioDeserializationFailed {
            get {
                return ResourceManager.GetString("ScenarioDeserializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScenarioRebuildingError.
        /// </summary>
        public static string ScenarioRebuildingError {
            get {
                return ResourceManager.GetString("ScenarioRebuildingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScenarioSerializationFailed.
        /// </summary>
        public static string ScenarioSerializationFailed {
            get {
                return ResourceManager.GetString("ScenarioSerializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemGroupBox.
        /// </summary>
        public static string SystemGroupBox {
            get {
                return ResourceManager.GetString("SystemGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TargetScreenTip.
        /// </summary>
        public static string TargetScreenTip {
            get {
                return ResourceManager.GetString("TargetScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TruthButton.
        /// </summary>
        public static string TruthButton {
            get {
                return ResourceManager.GetString("TruthButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TruthButtonScreenTip.
        /// </summary>
        public static string TruthButtonScreenTip {
            get {
                return ResourceManager.GetString("TruthButtonScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnconditionalEffectStatement.
        /// </summary>
        public static string UnconditionalEffectStatement {
            get {
                return ResourceManager.GetString("UnconditionalEffectStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnconditionalEffectStatementActionError.
        /// </summary>
        public static string UnconditionalEffectStatementActionError {
            get {
                return ResourceManager.GetString("UnconditionalEffectStatementActionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnconditionalEffectStatementPostconditionError.
        /// </summary>
        public static string UnconditionalEffectStatementPostconditionError {
            get {
                return ResourceManager.GetString("UnconditionalEffectStatementPostconditionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnconditionalEffectStatementScreenTip.
        /// </summary>
        public static string UnconditionalEffectStatementScreenTip {
            get {
                return ResourceManager.GetString("UnconditionalEffectStatementScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnconditionalFluentReleaseStatement.
        /// </summary>
        public static string UnconditionalFluentReleaseStatement {
            get {
                return ResourceManager.GetString("UnconditionalFluentReleaseStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnconditionalFluentReleaseStatementActionError.
        /// </summary>
        public static string UnconditionalFluentReleaseStatementActionError {
            get {
                return ResourceManager.GetString("UnconditionalFluentReleaseStatementActionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnconditionalFluentReleaseStatementFluentError.
        /// </summary>
        public static string UnconditionalFluentReleaseStatementFluentError {
            get {
                return ResourceManager.GetString("UnconditionalFluentReleaseStatementFluentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnconditionalFluentReleaseStatementScreenTip.
        /// </summary>
        public static string UnconditionalFluentReleaseStatementScreenTip {
            get {
                return ResourceManager.GetString("UnconditionalFluentReleaseStatementScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnconditionalImpossibilityStatement.
        /// </summary>
        public static string UnconditionalImpossibilityStatement {
            get {
                return ResourceManager.GetString("UnconditionalImpossibilityStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnconditionalImpossibilityStatementActionError.
        /// </summary>
        public static string UnconditionalImpossibilityStatementActionError {
            get {
                return ResourceManager.GetString("UnconditionalImpossibilityStatementActionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnconditionalImpossibilityStatementScreenTip.
        /// </summary>
        public static string UnconditionalImpossibilityStatementScreenTip {
            get {
                return ResourceManager.GetString("UnconditionalImpossibilityStatementScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValueCondition.
        /// </summary>
        public static string ValueCondition {
            get {
                return ResourceManager.GetString("ValueCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValueConditionScreenTip.
        /// </summary>
        public static string ValueConditionScreenTip {
            get {
                return ResourceManager.GetString("ValueConditionScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValueQuery.
        /// </summary>
        public static string ValueQuery {
            get {
                return ResourceManager.GetString("ValueQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValueStatement.
        /// </summary>
        public static string ValueStatement {
            get {
                return ResourceManager.GetString("ValueStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValueStatementActionError.
        /// </summary>
        public static string ValueStatementActionError {
            get {
                return ResourceManager.GetString("ValueStatementActionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValueStatementConditionError.
        /// </summary>
        public static string ValueStatementConditionError {
            get {
                return ResourceManager.GetString("ValueStatementConditionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValueStatementScreenTip.
        /// </summary>
        public static string ValueStatementScreenTip {
            get {
                return ResourceManager.GetString("ValueStatementScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowTitle.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
