//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Localization.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddActionButton.
        /// </summary>
        public static string ActionDropDown {
            get {
                return ResourceManager.GetString("ActionDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddActionButton.
        /// </summary>
        public static string AddActionButton {
            get {
                return ResourceManager.GetString("AddActionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddActionClauseDropDown.
        /// </summary>
        public static string AddActionClauseDropDown {
            get {
                return ResourceManager.GetString("AddActionClauseDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddFluentButton.
        /// </summary>
        public static string AddFluentButton {
            get {
                return ResourceManager.GetString("AddFluentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddQueryClauseDropDown.
        /// </summary>
        public static string AddQueryClauseDropDown {
            get {
                return ResourceManager.GetString("AddQueryClauseDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlternativeButton.
        /// </summary>
        public static string AlternativeButton {
            get {
                return ResourceManager.GetString("AlternativeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalculateButton.
        /// </summary>
        public static string CalculateButton {
            get {
                return ResourceManager.GetString("CalculateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChooseLanguage.
        /// </summary>
        public static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClauseGroupBox.
        /// </summary>
        public static string ClauseGroupBox {
            get {
                return ResourceManager.GetString("ClauseGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClearButton.
        /// </summary>
        public static string ClearButton {
            get {
                return ResourceManager.GetString("ClearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloseButton.
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConjunctionButton.
        /// </summary>
        public static string ConjunctionButton {
            get {
                return ResourceManager.GetString("ConjunctionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditTab.
        /// </summary>
        public static string EditTab {
            get {
                return ResourceManager.GetString("EditTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EquivalencyButton.
        /// </summary>
        public static string EquivalenceButton {
            get {
                return ResourceManager.GetString("EquivalenceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExportButton.
        /// </summary>
        public static string ExportButton {
            get {
                return ResourceManager.GetString("ExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FluentDropDown.
        /// </summary>
        public static string FluentDropDown {
            get {
                return ResourceManager.GetString("FluentDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FormulaGroupBox.
        /// </summary>
        public static string FormulaGroupBox {
            get {
                return ResourceManager.GetString("FormulaGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImplicationButton.
        /// </summary>
        public static string ImplicationButton {
            get {
                return ResourceManager.GetString("ImplicationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImportButton.
        /// </summary>
        public static string ImportButton {
            get {
                return ResourceManager.GetString("ImportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LanguageGroupBox.
        /// </summary>
        public static string LanguageGroupBox {
            get {
                return ResourceManager.GetString("LanguageGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NegationButton.
        /// </summary>
        public static string NegationButton {
            get {
                return ResourceManager.GetString("NegationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptionsTab.
        /// </summary>
        public static string OptionsTab {
            get {
                return ResourceManager.GetString("OptionsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemGroupBox.
        /// </summary>
        public static string SystemGroupBox {
            get {
                return ResourceManager.GetString("SystemGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowTitle.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
